name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 2.4, 2.5, 2.6, 2.7, 3.0 ]

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        gem install bundler --no-document
        bundle install --jobs 4 --retry 3
        bundle exec rake
